# [productosBD]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [productosBD]    Script Date: 19/9/2025 1:25:30 ******/
CREATE DATABASE [productosBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'productosBD', FILENAME = N'C:\BD\SQL_SERVER\MSSQL16.MSQL_TITUSERVER\MSSQL\DATA\productosBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'productosBD_log', FILENAME = N'C:\BD\SQL_SERVER\MSSQL16.MSQL_TITUSERVER\MSSQL\DATA\productosBD_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [productosBD] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [productosBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [productosBD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [productosBD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [productosBD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [productosBD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [productosBD] SET ARITHABORT OFF 
GO
ALTER DATABASE [productosBD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [productosBD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [productosBD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [productosBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [productosBD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [productosBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [productosBD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [productosBD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [productosBD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [productosBD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [productosBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [productosBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [productosBD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [productosBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [productosBD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [productosBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [productosBD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [productosBD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [productosBD] SET  MULTI_USER 
GO
ALTER DATABASE [productosBD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [productosBD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [productosBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [productosBD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [productosBD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [productosBD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'productosBD', N'ON'
GO
ALTER DATABASE [productosBD] SET QUERY_STORE = ON
GO
ALTER DATABASE [productosBD] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[productos_Inventario]

In [0]:
USE [productosBD]
GO

In [0]:
/****** Object:  Table [dbo].[productos_Inventario]    Script Date: 19/9/2025 1:25:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[productos_Inventario](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nchar](30) NOT NULL,
	[descripcion] [nchar](50) NULL,
	[categoria] [nchar](20) NULL,
	[imagen] [varchar](max) NULL,
	[precio] [decimal](10, 2) NOT NULL,
	[stock] [int] NOT NULL,
 CONSTRAINT [PK_productos_Inventario] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[transacciones]

In [0]:
/****** Object:  Table [dbo].[transacciones]    Script Date: 19/9/2025 1:25:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[transacciones](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[fecha] [smalldatetime] NOT NULL,
	[tipoTransaccion] [nchar](10) NOT NULL,
	[idProducto] [int] NOT NULL,
	[cantidad] [int] NOT NULL,
	[precioUnitario] [decimal](10, 2) NOT NULL,
	[precioTotal] [decimal](10, 2) NOT NULL,
	[detalle] [nchar](30) NULL,
 CONSTRAINT [PK_transacciones] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [FK_productos_Inventario_productos_Inventario]

In [0]:
ALTER TABLE [dbo].[productos_Inventario]  WITH CHECK ADD  CONSTRAINT [FK_productos_Inventario_productos_Inventario] FOREIGN KEY([id])
REFERENCES [dbo].[productos_Inventario] ([id])
GO
ALTER TABLE [dbo].[productos_Inventario] CHECK CONSTRAINT [FK_productos_Inventario_productos_Inventario]
GO

# [FK_transacciones_productos_Inventario]

In [0]:
ALTER TABLE [dbo].[transacciones]  WITH CHECK ADD  CONSTRAINT [FK_transacciones_productos_Inventario] FOREIGN KEY([idProducto])
REFERENCES [dbo].[productos_Inventario] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[transacciones] CHECK CONSTRAINT [FK_transacciones_productos_Inventario]
GO

# [productosBD]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [productosBD] SET  READ_WRITE 
GO